apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r88diu9h8-go
  janus-idp.io/tekton: r88diu9h8-go
  backstage.io/kubernetes-id: r88diu9h8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r88diu9h8-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
